name: yeniapex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  # Backend & Realtime
  supabase_flutter: ^2.8.3
  livekit_client: ^2.2.6  # ğŸ”¥ DÃ¼ÅŸÃ¼rÃ¼ldÃ¼ (flutter_webrtc uyumluluÄŸu iÃ§in)
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.0.1
  wakelock_plus: ^1.4.0
  audioplayers: ^6.0.0
  flutter_webrtc: ^0.11.7
  
  http: ^1.2.2

  # State Management & Utils
  get: ^4.6.6
  permission_handler: ^11.3.1
  intl: ^0.19.0
  device_info_plus: ^12.3.0

  # UI & Assets
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  extended_image: ^10.0.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  glassmorphism: ^3.0.0
  lottie: ^3.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.5.0
  
  # Posts Feature
  timeago: ^3.7.0
  uuid: ^4.5.1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/sounds/
    - assets/icons/
    - assets/images/
